/**
 * This file is auto-generated by `npm run db:types`.
 * Run `npm run db:sync` after updating Supabase migrations to keep it up to date.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "13.0.5"
  }
  public: {
    Tables: {
      chapter_entries: {
        Row: {
          body: Json
          chapter_id: string
          created_at: string
          date_granularity: Database["public"]["Enums"]["chapter_entry_date_granularity"]
          entry_date: string | null
          entry_type: Database["public"]["Enums"]["chapter_entry_type"]
          id: string
          status: Database["public"]["Enums"]["chapter_entry_status"]
          summary: string | null
          title: string
          updated_at: string
        }
        Insert: {
          body?: Json
          chapter_id: string
          created_at?: string
          date_granularity?: Database["public"]["Enums"]["chapter_entry_date_granularity"]
          entry_date?: string | null
          entry_type: Database["public"]["Enums"]["chapter_entry_type"]
          id?: string
          status?: Database["public"]["Enums"]["chapter_entry_status"]
          summary?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          body?: Json
          chapter_id?: string
          created_at?: string
          date_granularity?: Database["public"]["Enums"]["chapter_entry_date_granularity"]
          entry_date?: string | null
          entry_type?: Database["public"]["Enums"]["chapter_entry_type"]
          id?: string
          status?: Database["public"]["Enums"]["chapter_entry_status"]
          summary?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "chapter_entries_chapter_id_fkey"
            columns: ["chapter_id"]
            isOneToOne: false
            referencedRelation: "user_chapters"
            referencedColumns: ["id"]
          },
        ]
      }
      interview_entries: {
        Row: {
          entry_id: string
          id: string
          interview_id: string
        }
        Insert: {
          entry_id: string
          id?: string
          interview_id: string
        }
        Update: {
          entry_id?: string
          id?: string
          interview_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "interview_entries_entry_id_fkey"
            columns: ["entry_id"]
            isOneToOne: true
            referencedRelation: "chapter_entries"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "interview_entries_interview_id_fkey"
            columns: ["interview_id"]
            isOneToOne: false
            referencedRelation: "user_interviews"
            referencedColumns: ["id"]
          },
        ]
      }
      interview_messages: {
        Row: {
          author: Database["public"]["Enums"]["interview_message_author"]
          body: string
          id: string
          interview_id: string
          sequence: number
          ts: string
        }
        Insert: {
          author: Database["public"]["Enums"]["interview_message_author"]
          body: string
          id?: string
          interview_id: string
          sequence?: number
          ts?: string
        }
        Update: {
          author?: Database["public"]["Enums"]["interview_message_author"]
          body?: string
          id?: string
          interview_id?: string
          sequence?: number
          ts?: string
        }
        Relationships: [
          {
            foreignKeyName: "interview_messages_interview_id_fkey"
            columns: ["interview_id"]
            isOneToOne: false
            referencedRelation: "user_interviews"
            referencedColumns: ["id"]
          },
        ]
      }
      user_chapters: {
        Row: {
          created_at: string
          description: string | null
          end_date: string | null
          id: string
          start_date: string | null
          title: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          end_date?: string | null
          id?: string
          start_date?: string | null
          title: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          description?: string | null
          end_date?: string | null
          id?: string
          start_date?: string | null
          title?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_chapters_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      user_interviews: {
        Row: {
          closed_at: string | null
          created_at: string
          id: string
          status: Database["public"]["Enums"]["user_interview_status"]
          user_id: string
        }
        Insert: {
          closed_at?: string | null
          created_at?: string
          id?: string
          status?: Database["public"]["Enums"]["user_interview_status"]
          user_id: string
        }
        Update: {
          closed_at?: string | null
          created_at?: string
          id?: string
          status?: Database["public"]["Enums"]["user_interview_status"]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_interviews_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          created_at: string
          first_name: string | null
          id: string
          last_name: string | null
          onboarding_complete: boolean
          updated_at: string
        }
        Insert: {
          created_at?: string
          first_name?: string | null
          id: string
          last_name?: string | null
          onboarding_complete?: boolean
          updated_at?: string
        }
        Update: {
          created_at?: string
          first_name?: string | null
          id?: string
          last_name?: string | null
          onboarding_complete?: boolean
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      chapter_entry_date_granularity: "day" | "month" | "year"
      chapter_entry_status: "draft" | "published" | "archived"
      chapter_entry_type: "milestone" | "memory" | "story"
      interview_message_author: "user" | "chat_interviewer"
      user_interview_status: "in_progress" | "closed"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      chapter_entry_date_granularity: ["day", "month", "year"],
      chapter_entry_status: ["draft", "published", "archived"],
      chapter_entry_type: ["milestone", "memory", "story"],
      interview_message_author: ["user", "chat_interviewer"],
      user_interview_status: ["in_progress", "closed"],
    },
  },
} as const
