#!/usr/bin/env node
import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { resolve, relative } from "node:path";

const root = process.cwd();
const args = process.argv.slice(2);
const runPush = !args.includes("--types-only");
const runTypes = !args.includes("--push-only");
const schemaList = (process.env.SUPABASE_DB_SCHEMAS ?? "public")
  .split(",")
  .map((schema) => schema.trim())
  .filter(Boolean);

if (!schemaList.length) {
  console.error(
    "No schemas supplied. Set SUPABASE_DB_SCHEMAS or keep the default ('public').",
  );
  process.exit(1);
}

const typesOutputPath = resolve(
  root,
  process.env.SUPABASE_TYPES_PATH ?? "src/lib/supabase/types.ts",
);
const target = (process.env.SUPABASE_DB_TARGET ?? "linked").toLowerCase();

function buildTargetArgs() {
  if (target === "linked") {
    return ["--linked"];
  }
  if (target === "local") {
    return ["--local"];
  }
  if (target === "db-url") {
    const dbUrl = process.env.SUPABASE_DB_URL;
    if (!dbUrl) {
      console.error(
        "SUPABASE_DB_URL is required when SUPABASE_DB_TARGET=db-url.",
      );
      process.exit(1);
    }
    return ["--db-url", dbUrl];
  }
  console.error(
    `Unknown SUPABASE_DB_TARGET "${target}". Use "linked", "local", or "db-url".`,
  );
  process.exit(1);
}

function runCommand(commandArgs, options = {}) {
  const result = spawnSync("supabase", commandArgs, {
    stdio: options.captureStdout ? ["ignore", "pipe", "inherit"] : "inherit",
    encoding: "utf-8",
  });
  if (result.error) {
    console.error(result.error.message);
    process.exit(result.status ?? 1);
  }
  if (result.status !== 0) {
    process.exit(result.status);
  }
  return result.stdout;
}

if (runPush) {
  console.log(
    `→ Applying Supabase migrations (${target}) via supabase db push...`,
  );
  runCommand(["db", "push", ...buildTargetArgs()]);
}

if (runTypes) {
  console.log("→ Regenerating Supabase TypeScript types...");
  const schemaArgs = schemaList.flatMap((schema) => ["--schema", schema]);
  const stdout = runCommand(
    ["gen", "types", "typescript", ...schemaArgs, ...buildTargetArgs()],
    { captureStdout: true },
  );

  const banner =
    "/**\n" +
    " * This file is auto-generated by `npm run db:types`.\n" +
    " * Run `npm run db:sync` after updating Supabase migrations to keep it up to date.\n" +
    " */\n";

  writeFileSync(typesOutputPath, `${banner}\n${stdout.trim()}\n`);
  console.log(
    `✔ Wrote Supabase types to ${relative(root, typesOutputPath)} (${schemaList.join(", ")})`,
  );
}
