-- Schema objects to power AI interview flows.

begin;

-- Domain enums --------------------------------------------------------------

do $$
begin
  if not exists (
    select 1 from pg_type where typname = 'user_interview_status'
  ) then
    create type public.user_interview_status as enum (
      'in_progress',
      'closed'
    );
  end if;

  if not exists (
    select 1 from pg_type where typname = 'interview_message_author'
  ) then
    create type public.interview_message_author as enum (
      'user',
      'chat_interviewer'
    );
  end if;
end;
$$;

-- Helper to automatically backfill closed_at when an interview is closed.
create or replace function public.set_user_interviews_closed_at()
returns trigger
language plpgsql
as $$
begin
  if new.status = 'closed' then
    if new.closed_at is null then
      new.closed_at = timezone('utc', now());
    end if;
  elsif new.status = 'in_progress' then
    if new.closed_at is not null then
      new.closed_at = null;
    end if;
  end if;
  return new;
end;
$$;

-------------------------------------------------------------------------------
-- Interviews

create table if not exists public.user_interviews (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users (id) on delete cascade,
  status public.user_interview_status not null default 'in_progress',
  created_at timestamptz not null default timezone('utc', now()),
  closed_at timestamptz,
  constraint user_interviews_closed_at_check
    check (
      (status = 'closed' and closed_at is not null)
      or (status = 'in_progress' and closed_at is null)
    )
);

comment on table public.user_interviews is 'Top-level interview sessions between a user and the AI interviewer.';

create index if not exists user_interviews_user_idx
  on public.user_interviews (user_id);

alter table public.user_interviews enable row level security;

create policy "Users can read their interviews"
  on public.user_interviews
  for select
  using (user_id = auth.uid());

create policy "Users manage their interviews"
  on public.user_interviews
  for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create trigger set_user_interviews_closed_at
before insert or update on public.user_interviews
for each row
execute procedure public.set_user_interviews_closed_at();

-------------------------------------------------------------------------------
-- Interview messages

create table if not exists public.interview_messages (
  id uuid primary key default gen_random_uuid(),
  sequence bigint generated by default as identity,
  interview_id uuid not null references public.user_interviews (id) on delete cascade,
  ts timestamptz not null default timezone('utc', now()),
  body text not null,
  author public.interview_message_author not null,
  constraint interview_messages_sequence_unique unique (sequence)
);

comment on table public.interview_messages is 'Threaded QA content exchanged during an interview session.';

create index if not exists interview_messages_interview_idx
  on public.interview_messages (interview_id, sequence);

alter table public.interview_messages enable row level security;

create policy "Users can read their interview messages"
  on public.interview_messages
  for select
  using (
    exists (
      select 1
      from public.user_interviews ui
      where ui.id = interview_messages.interview_id
        and ui.user_id = auth.uid()
    )
  );

create policy "Users can insert interview messages"
  on public.interview_messages
  for insert
  with check (
    exists (
      select 1
      from public.user_interviews ui
      where ui.id = interview_messages.interview_id
        and ui.user_id = auth.uid()
    )
  );

-------------------------------------------------------------------------------
-- Interview entries

create table if not exists public.interview_entries (
  id uuid primary key default gen_random_uuid(),
  interview_id uuid not null references public.user_interviews (id) on delete cascade,
  entry_id uuid not null references public.chapter_entries (id) on delete cascade,
  unique (entry_id)
);

comment on table public.interview_entries is 'Links auto-generated chapter entries back to the interviews that produced them.';

create index if not exists interview_entries_interview_idx
  on public.interview_entries (interview_id);

alter table public.interview_entries enable row level security;

create policy "Users can read their interview entries"
  on public.interview_entries
  for select
  using (
    exists (
      select 1
      from public.user_interviews ui
      where ui.id = interview_entries.interview_id
        and ui.user_id = auth.uid()
    )
  );

create policy "Users can manage their interview entries"
  on public.interview_entries
  for all
  using (
    exists (
      select 1
      from public.user_interviews ui
      where ui.id = interview_entries.interview_id
        and ui.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.user_interviews ui
      where ui.id = interview_entries.interview_id
        and ui.user_id = auth.uid()
    )
  );

commit;
