begin;

do $$
begin
  if exists (
    select 1
    from pg_type t
    join pg_enum e on e.enumtypid = t.oid
    where t.typname = 'interview_message_author'
      and e.enumlabel = 'chat_interviewer'
  ) then
    alter type public.interview_message_author rename value 'chat_interviewer' to 'interviewer';
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_type where typname = 'user_interview_mode'
  ) then
    create type public.user_interview_mode as enum ('chat', 'voice');
  end if;
end $$;

alter table public.user_interviews
add column if not exists mode public.user_interview_mode not null default 'chat';

comment on column public.user_interviews.mode is
  'How this interview session is conducted in the product UI.';

do $$
begin
  if not exists (
    select 1 from pg_type where typname = 'interview_realtime_event_origin'
  ) then
    create type public.interview_realtime_event_origin as enum ('client', 'server', 'app');
  end if;
end $$;

create table if not exists public.interview_realtime_events (
  id uuid primary key default gen_random_uuid(),
  sequence bigint generated by default as identity,
  interview_id uuid not null references public.user_interviews (id) on delete cascade,
  interview_message_id uuid references public.interview_messages (id) on delete set null,
  origin public.interview_realtime_event_origin not null,
  type text not null,
  summary text,
  payload jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

comment on table public.interview_realtime_events is
  'Important client/server/app events captured during a voice interview session for debugging and replay.';

create index if not exists interview_realtime_events_interview_idx
  on public.interview_realtime_events (interview_id, sequence);

create index if not exists interview_realtime_events_created_at_idx
  on public.interview_realtime_events (interview_id, created_at);

alter table public.interview_realtime_events enable row level security;

create policy "Users can read their realtime interview events"
  on public.interview_realtime_events
  for select
  using (
    exists (
      select 1
      from public.user_interviews ui
      where ui.id = interview_realtime_events.interview_id
        and ui.user_id = auth.uid()
    )
  );

create policy "Users can insert their realtime interview events"
  on public.interview_realtime_events
  for insert
  with check (
    exists (
      select 1
      from public.user_interviews ui
      where ui.id = interview_realtime_events.interview_id
        and ui.user_id = auth.uid()
    )
    and (
      interview_realtime_events.interview_message_id is null
      or exists (
        select 1
        from public.interview_messages im
        where im.id = interview_realtime_events.interview_message_id
          and im.interview_id = interview_realtime_events.interview_id
      )
    )
  );

commit;
